name: yarn-upgrade-minor 


on:
  schedule:
  - cron: "0 0 1-31 * *" 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i -g yarn
      - run: yarn
      - run: yarn yarn-upgrade-minor --non-interactive > console.log
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python replace.py
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN_APP }}
          empty: false
          branch: master
          message: 'update lib via action'
      - uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: ${{github.repository}} Github Actions job result
          # Required recipients' addresses:
          to: ${{secrets.MAIL_TO}}
          # Required sender full name (address can be skipped):
          from: GIT # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          attachments:  console.log, package.json
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
