name: yarn-upgrade-minor 


on:
  schedule:
  - cron: "0 0 1 * *" 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo 'TOKEN=${{ secrets.TOKEN_APP }}' >> $GITHUB_ENV
      - run: echo 'MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}' >> $GITHUB_ENV
      - run: echo 'MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}' >> $GITHUB_ENV
      - run: echo 'MAIL_TO=${{ secrets.MAIL_TO }}' >> $GITHUB_ENV
      - uses: Argragas/js-check-update-action@v1.7
        with:
          TOKEN_APP:  ${{ env.TOKEN }}
          MAIL_USERNAME:  ${{ env.MAIL_USERNAME }}
          MAIL_PASSWORD:  ${{ env.MAIL_PASSWORD }}
          MAIL_TO:  ${{ env.MAIL_TO }}
